//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class socios
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Cedula { get; set; }
        public string Foto { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Sexo { get; set; }
        public string Edad { get; set; }
        public string Fecha_de_nacimiento { get; set; }
        public string Afiliados { get; set; }
        public string Datos_Membresia { get; set; }
        public string Lugar_de_trabajo { get; set; }
        public string Direccion_Oficina { get; set; }
        public string Telefono_Oficina { get; set; }
        public string Estado_Membresia { get; set; }
        public string Fecha_de_ingreso { get; set; }
        public string Fecha_de_salida { get; set; }
    }
}
